// <auto-generated />
using System;
using DataAccess.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace B2B.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Entity.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CODE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UNIT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UNIT1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UNIT1RATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("UNIT2")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UNIT2RATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("UNIT3")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UNIT3RATE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateUser")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ecec644-9adc-4b78-a4b9-e011f8106a1a"),
                            CODE = "st1",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7456),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7458),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("eecbd0a4-8864-4cac-9a43-9fb9327bb48b"),
                            CODE = "st2",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7466),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "2 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7468),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("8b9b962a-f91a-454a-9759-29181f355441"),
                            CODE = "st3",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7474),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7476),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("c026830d-ba47-40ae-8aef-7e3773040818"),
                            CODE = "st4",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7498),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7500),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("f6a9ba55-07d4-44e5-913f-3981e5cad11f"),
                            CODE = "st5",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7506),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7508),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("631239c4-3dc0-4464-9c01-243169a4400e"),
                            CODE = "st6",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7514),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7516),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("1861d5b1-2f47-498a-8a94-32904b5f7cef"),
                            CODE = "st7",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7522),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7524),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("dc4e0bfa-30f7-42ff-be09-1af025078c64"),
                            CODE = "st8",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7530),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7532),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("e9f6655c-a514-45fc-993c-a4f8664abb53"),
                            CODE = "st9",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7538),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7540),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("6766539f-c507-449e-a112-7820180db4fb"),
                            CODE = "st10",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7545),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7547),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("622b34f3-86eb-4380-a0e0-190eee1bd337"),
                            CODE = "st11",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7552),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7554),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("4b328075-2f27-4035-a871-02b260a18024"),
                            CODE = "st12",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7566),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7568),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("ab7b129e-8b4e-4ef4-816a-548552ea2d89"),
                            CODE = "st13",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7574),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7576),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("9fd74662-54bb-4f45-8a5e-081b89cfdeba"),
                            CODE = "st14",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7581),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7582),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("5ea8289b-1056-4b06-8b4f-7568c63b384c"),
                            CODE = "st15",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7587),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7588),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("9127af94-11d7-46a7-8f33-776b21b7c760"),
                            CODE = "st16",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7591),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7592),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("cbc0bfae-5338-4ba2-8cf0-72326e53738d"),
                            CODE = "st17",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7594),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7595),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("776b080b-d9c2-4715-ab94-0320c9325af5"),
                            CODE = "st18",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7599),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7601),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("7c209914-590e-4e06-89c0-4e48d5d8ebae"),
                            CODE = "st19",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7606),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7607),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("c9269bf1-0efa-41c2-ae95-1eb60edcb93c"),
                            CODE = "st20",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7616),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7618),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("f4672cf5-707a-45db-8cf5-18eea38a4275"),
                            CODE = "st21",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7623),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7625),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("41496638-3ca5-403a-adc4-dd5bf09203e6"),
                            CODE = "st22",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7630),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7632),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("af23ebc6-1982-4607-9b0a-ced0561b87dc"),
                            CODE = "st23",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7636),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7638),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("6c37b46f-1c2f-48b3-864b-325374c079c7"),
                            CODE = "st24",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7643),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7645),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("eb12a87f-abe7-4d96-b155-60fa17447015"),
                            CODE = "st25",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7649),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7651),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("c991f8a1-9f68-4a0a-92b2-eb26d4b3ca16"),
                            CODE = "st26",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7656),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7658),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("7479a2cf-f7f0-47af-9be2-8aad88f66cb0"),
                            CODE = "st27",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7663),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7665),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("74129ace-6c50-495b-93eb-72c4095a923c"),
                            CODE = "st28",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7675),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7676),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("cdcd6401-22eb-4939-9559-6b9b6c2699d0"),
                            CODE = "st29",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7682),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7683),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("e3d755b7-0c53-41e2-a132-7b78b4cfd877"),
                            CODE = "st30",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7688),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7690),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("4bf39c76-1771-4be1-97be-a366559215ab"),
                            CODE = "st31",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7695),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7697),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("101b7ea8-ca48-4372-9f38-aa7ba22c7ea8"),
                            CODE = "st32",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7702),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7704),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("4164da50-e6cf-4638-b51b-45eea1802ec0"),
                            CODE = "st33",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7709),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7710),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("c904e213-59b4-42f5-bdaf-ea262a6b43ad"),
                            CODE = "st34",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7715),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7715),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("a251f52e-fad0-433a-9189-0743e640ffa7"),
                            CODE = "st35",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7717),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7718),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("01339499-2821-4943-89d1-9813d7945269"),
                            CODE = "st36",
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7724),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            NAME = "1 nolu urun",
                            UNIT = "adet",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7725),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        });
                });

            modelBuilder.Entity("Entity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateUser")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d83f64b-52eb-401a-baa7-eabc59bbabeb"),
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7128),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            RoleName = "Admin",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7142),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        },
                        new
                        {
                            Id = new Guid("01df900c-1de8-43a6-b270-a72c1bebf1da"),
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7176),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            RoleName = "User",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7178),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0")
                        });
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            CreateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7246),
                            CreateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            Email = "murat@ulkubilgisayar.com",
                            Password = "Admin",
                            UpdateDate = new DateTime(2023, 9, 13, 11, 18, 47, 733, DateTimeKind.Local).AddTicks(7249),
                            UpdateUser = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("Entity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("29bcfcd7-b5e7-4b57-9a71-2d64ea6998a0"),
                            RoleId = new Guid("0d83f64b-52eb-401a-baa7-eabc59bbabeb")
                        });
                });

            modelBuilder.Entity("Entity.UserRole", b =>
                {
                    b.HasOne("Entity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.User", "User")
                        .WithMany("UsersRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.Navigation("UsersRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
